---
version: '2'

services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      ENVIRONMENT: development
    volumes:
      - .:/var/www/html:delegated
    ports:
      - 8080:80
      - 8443:443